### ISSUE TITLE
If the client maliciously manipulate the input DeltaTime, won't it skew the simulation? (Speed hack)

### ISSUE THREAD

**Issue by astutejoe** [MultiplayerBook/MultiplayerBook#16]
I'm implementing a shooter based on the teachings of the book (I have a physical copy) and many other reading materials. The problem I'm facing now is that a malicious client can trivially manipulate the DeltaTime in the input packets resulting in a speed hack.

The way I've tackled this is by calculating/inferring the DeltaTime between input packets and punishing/kicking the player if it diverges too much from the self-proclaimed input DeltaTime.

This really feels like a hack though and can easily fall apart if the player is dropping packets as the inferred DeltaTime will be completely off.

Am I missing something? (I just checked the Chapter 8 code and it looks susceptible)

Cheers :)

**Comment by JoshuaGlazer** [comment]
Hi Gabriel!

Good point- I don't think you're missing anything.  I totally agree that as written the server is subject to a client spoofing the timestamp in their move.  Have you considered having the server ignore client moves that claim to be from too far in the future?  You can either drop them, or hold onto them until it would be appropriate to process them? (and if the moves come from too far in the future consistently, drop the client for cheating, like you say). Similarly, you can drop moves (and notify the client they were dropped) that arrive too late relative to their time stamp.  I think this is similar to what you're suggesting, but relies on comparing timestamps to how long the game has been running on the server, rather than the time between packets (which, like you say, is a little less stable).  I agree it starts to get a little finicky regardless, but I think you can tune to something that feels fair from both the perspective of the player and the server trying to avoid cheating.

Cheers!
Josh
