### ISSUE TITLE
dyld: Library not loaded: @executable_path/libSDL2_ttf-2.0.0.dylib

### ISSUE THREAD

**Issue by AttoLee** [MultiplayerBook/MultiplayerBook#4]
I try run RoboCatRTS of chapter 6, archive the project, export with the option "Save Built Products" to Desktop, in terminal, try ``./RoboCatRTS 45000 John``,

Then got this error:
``dyld: Library not loaded: @executable_path/libSDL2_ttf-2.0.0.dylib
  Referenced from: /Users/apple/Desktop/RoboCatRTS 2016-02-28 22-31-15/Products/usr/local/bin/./RoboCatRTS
  Reason: image not found``

This is first time I archive c++ project in xcode, I don't sure whether those steps are right.

**Comment by chalonverse** [comment]
The issue is that when you build the executable, there also are several other dylib library files that are copied into the executable directory as well. So if you just export with "Save Built Products," I suspect it would only copy the executable and not the additional files.

There are two ways to fix this:
1. Browse to the default build directory and run the executable from there. It's going to be a subdirectory in ~/Library/Developer/Xcode/DerivedData/ and then you'll find a RoboCatRTS folder and it'll be somewhere under a couple of other subdirectories. You can also right click on the RoboCatRTS build product in the Xcode project view and find it in the finder, if you're having trouble finding the path.
2. You can also change the default build output folder to, for example, be relative to the project/source root, see: https://developer.apple.com/library/ios/recipes/xcode_help-locations_preferences/Build/Build.html. Then just run it from there.
