### ISSUE TITLE
Hello, I have a question in Chapter 6 RoboCatRTS again.

### ISSUE THREAD

**Issue by insooneelife** [MultiplayerBook/MultiplayerBook#8]
Thank you for giving answer for my question.
It greatly helped me to understand that source.

But I have more question in here.
In RoboCat class, in UpdateAttackState method, if statement.

if ( distSq <= kAttackRangeSq )
{
	...
	GameObjectPtr me = NetworkManager::sInstance->GetGameObject( mNetworkId );
	...
	yarn->InitFromShooter( me, mTargetCat );
}

I have question in here.
1. Is there any reason for finding instance in map rather than using this pointer?
2. Because of the name, I thought that "mNetworkId" was identifier that grouping entities by networks.
But It seems like just entity id which is unique for query them.  Is it right? or am I missing something?

**Comment by chalonverse** [comment]
1. Mainly it's because the functions want a shared pointer, and if we just used this, it would be a raw pointer and not a shared one. Another (possibly better) way to solve it would be to make the GameObject class inherit from std::enable_shared_from_this, which then allows the shared_from_this function to be called to get a shared pointer to this.

2. The network ID is just a unique object ID, yes. It's called a "network" ID because it's guaranteed that for example this RoboCat has the same network ID on all other peers.
